#!/usr/bin/env python3
# This skript has been generated by Claude.ai
"""
extend_rou_file.py

Extend a SUMO / Eclipse MOSAIC route file (e.g. berlin.rou.gz from the
BeST scenario) beyond its original time horizon by cloning a slice of
existing trips and replaying them later in the simulation.

WHY THIS APPROACH
------------------
BeST only contains demand for one 24h day (depart values from 0 up to
just under 86400s). There's no "real" demand for what happens after
that, so the usual trick in SUMO/MOSAIC workflows is to reuse an
existing, plausible slice of the day and time-shift it into the new
window instead of inventing traffic from nothing.

By default this script takes the first N seconds of the day (the quiet
early-morning hours, depart in [0, new_end - old_end)) and appends them
shifted by +old_end, so the file now also has plausible demand up to
new_end. Use --source-start to loop a different window instead (e.g.
the evening hours) if that fits your use case better.

Notes:
- Works on plain .rou.xml or gzipped .rou.gz (detected by extension).
- Streams through the file (bounded memory) so it's safe to run on the
  full ~2.25M-trip berlin.rou.gz - it will just take a while (I/O and
  XML (re)serialization bound; expect several minutes to tens of
  minutes depending on your machine).
- Only needs the Python standard library.
- For simplicity the output root tag is written as plain <routes> -
  any xsi:schemaLocation hint on the original root is dropped. This is
  purely cosmetic (an editor/validator hint) and is not required for
  SUMO or MOSAIC to load the file.
- If your scenario has a *separate* route file for buses, run this
  script on that file too if you want buses running past 24h as well.

USAGE
-----
    python extend_rou_file.py berlin.rou.gz berlin_extended.rou.gz

    # equivalent, explicit:
    python extend_rou_file.py berlin.rou.gz berlin_extended.rou.gz \
        --old-end 86400 --new-end 104400

    # loop the evening hours (19:00-24:00) instead of early morning:
    python extend_rou_file.py berlin.rou.gz berlin_extended.rou.gz \
        --source-start 68400
"""

import argparse
import gzip
import sys
import xml.etree.ElementTree as ET

# tag -> (start-time attribute, end-time attribute or None)
TIME_TAGS = {
    "vehicle": ("depart", None),
    "trip": ("depart", None),
    "person": ("depart", None),
    "flow": ("begin", "end"),
}


def open_any(path, mode):
    return gzip.open(path, mode) if path.endswith(".gz") else open(path, mode)


def extend_route_file(in_path, out_path, old_end, new_end, source_start, id_prefix):
    needed = new_end - old_end
    if needed <= 0:
        raise ValueError("--new-end must be greater than --old-end")
    source_end = source_start + needed

    n_total = 0
    n_cloned = 0
    clones = []

    with open_any(in_path, "rt") as fin, open_any(out_path, "wt") as fout:
        context = ET.iterparse(fin, events=("start", "end"))
        _, root = next(context)  # consume the <routes ...> start tag

        fout.write('<?xml version="1.0" encoding="UTF-8"?>\n')
        fout.write("<routes>\n")

        depth = 0
        for event, elem in context:
            if event == "start":
                depth += 1
                continue

            # event == "end"
            if depth == 1:  # elem is a direct child of <routes>
                begin_attr, end_attr = TIME_TAGS.get(elem.tag, (None, None))

                if begin_attr is not None and elem.get(begin_attr) is not None:
                    try:
                        t = float(elem.get(begin_attr))
                    except ValueError:
                        t = None  # e.g. depart="triggered"
                    if t is not None and source_start <= t < source_end:
                        clone = ET.fromstring(ET.tostring(elem))
                        clone.set("id", f"{id_prefix}{clone.get('id')}")
                        clone.set(begin_attr, f"{t + old_end:.2f}")
                        if end_attr is not None and clone.get(end_attr) is not None:
                            clone.set(end_attr, f"{float(clone.get(end_attr)) + old_end:.2f}")
                        clones.append(ET.tostring(clone, encoding="unicode"))
                        n_cloned += 1

                fout.write(ET.tostring(elem, encoding="unicode"))
                fout.write("\n")
                n_total += 1
                if n_total % 200_000 == 0:
                    print(f"  ...processed {n_total:,} entries, cloned {n_cloned:,}", file=sys.stderr)

                elem.clear()
                root.clear()

            depth -= 1

        for c in clones:
            fout.write(c)
            fout.write("\n")
        fout.write("</routes>\n")

    return n_total, n_cloned


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("input", help="input route file, e.g. berlin.rou.gz or berlin.rou.xml")
    ap.add_argument("output", help="output route file, e.g. berlin_extended.rou.gz")
    ap.add_argument("--old-end", type=float, default=86400, help="current end of demand, seconds (default: 86400)")
    ap.add_argument("--new-end", type=float, default=104400, help="desired new end, seconds (default: 104400)")
    ap.add_argument(
        "--source-start", type=float, default=0,
        help="start of the window (in original seconds) to copy trips from "
             "(default: 0, i.e. reuse the quiet early-morning hours)",
    )
    ap.add_argument("--id-prefix", default="ext_", help="prefix added to cloned vehicle/trip ids (default: ext_)")
    args = ap.parse_args()

    window_end = args.source_start + (args.new_end - args.old_end)
    print(
        f"Extending {args.old_end:.0f}s -> {args.new_end:.0f}s by looping depart in "
        f"[{args.source_start:.0f}, {window_end:.0f})s from {args.input} ..."
    )

    n_total, n_cloned = extend_route_file(
        args.input, args.output, args.old_end, args.new_end, args.source_start, args.id_prefix
    )

    print(f"Done. Copied {n_total:,} original entries, added {n_cloned:,} shifted clones.")
    print(f"Output written to {args.output}")


if __name__ == "__main__":
    main()
