# AI-generated code — 2026-09-28

import sys
from pathlib import Path

EBUS_ROOT = Path(__file__).resolve().parents[1]

if str(EBUS_ROOT) not in sys.path:
    sys.path.insert(0, str(EBUS_ROOT))

from energy_storage_system.charging_station import ChargingStation
from energy_storage_system.energy_storage_system import EnergyStorageSystem


TOOLS_ROOT = Path(__file__).resolve().parent
EBUS_ROOT = TOOLS_ROOT.parent
SCENARIO_ROOT = EBUS_ROOT.parent

SUMO_DIR = SCENARIO_ROOT / "sumo"
EBUS_DIR = SCENARIO_ROOT / "eBuS"
PV_DATA_DIR = EBUS_DIR / "pv_estimation/data"

def run_energy_storage_system( run_dir: Path, start_date: str, seed: int):
    """
    Build the energy storage system profile from a seed run's SUMO
    chargingstations output (a "<seed>_directory" folder, see
    tools.order_output.order_output) and write the result back as XML.
    Uses the PV data fetched for start_date by run_pvgis_api_call.
    """
    run_dir = Path(run_dir)
    chargingstations_file = run_dir / f"{seed}_multirun_chargingstations.xml"
    output_file = run_dir / f"{seed}_multirun_ess.xml"
    pv_csv_path = PV_DATA_DIR / f"{start_date}_solar_power_v6_scaled.csv"

    EnergyStorageSystem(
        charging_stations=ChargingStation.from_xml(chargingstations_file),
        ess_factor=4.0,  # each station's ESS = ess_factor * that station's Peak Power (kWh)
        pv_csv_path=pv_csv_path,
        output_path=output_file,
        start_soc=0.2,  # fraction (0.0-1.0) of each station's own ESS capacity
        pv_factor=1.0,  # scales the PV power generated by each station
        grid_charge_max_soc=0.6,  # always draw from grid below this fraction of SoC
        grid_charge_power=50.0,  # power (kW) drawn from grid while below grid_charge_max_soc
        efficiency=0.95,  # battery round-trip efficiency (0.0-1.0)
    ).main()
    print(f"ESS output written to {output_file}")


if __name__ == "__main__":
    run_energy_storage_system(r"G:\Dokumente\Studium\FU Berlin\BeSTeBuS\best-ebus\scenario\sumo\output\grid_soc_run_2026-09-24-00-05-15\65_directory","2024-02-22",65)
    run_energy_storage_system(r"G:\Dokumente\Studium\FU Berlin\BeSTeBuS\best-ebus\scenario\sumo\output\grid_soc_run_2026-09-24-00-05-15\67_directory","2024-02-22",67)
    run_energy_storage_system(r"G:\Dokumente\Studium\FU Berlin\BeSTeBuS\best-ebus\scenario\sumo\output\grid_soc_run_2026-09-24-00-05-15\68_directory","2024-02-22",68)
    run_energy_storage_system(r"G:\Dokumente\Studium\FU Berlin\BeSTeBuS\best-ebus\scenario\sumo\output\grid_soc_run_2026-09-24-00-05-15\70_directory","2024-02-22",70)
    run_energy_storage_system(r"G:\Dokumente\Studium\FU Berlin\BeSTeBuS\best-ebus\scenario\sumo\output\grid_soc_run_2026-09-24-00-05-15\75_directory","2024-02-22",75)
