erDiagram
    battery {
        VARCHAR timestep_time
        VARCHAR vehicle_id
        FLOAT vehicle_energyConsumed
        FLOAT vehicle_totalEnergyConsumed
        FLOAT vehicle_totalEnergyRegenerated
        FLOAT vehicle_actualBatteryCapacity
        FLOAT vehicle_maximumBatteryCapacity
        VARCHAR vehicle_chargingStationId
        FLOAT vehicle_energyCharged
        FLOAT vehicle_energyChargedInTransit
        FLOAT vehicle_energyChargedStopped
        FLOAT vehicle_speed
        FLOAT vehicle_acceleration
        DOUBLE vehicle_x
        DOUBLE vehicle_y
        VARCHAR vehicle_lane
        FLOAT vehicle_posOnLane
        INTEGER vehicle_timeStopped
        VARCHAR simulation_timestamp
    }
    chargingstations {
        VARCHAR chargingStation_id
        FLOAT chargingStation_totalEnergyCharged
        INTEGER chargingStation_chargingSteps
        VARCHAR vehicle_id
        VARCHAR vehicle_type
        FLOAT vehicle_totalEnergyChargedIntoVehicle
        VARCHAR vehicle_chargingBegin
        VARCHAR vehicle_chargingEnd
        VARCHAR step_time
        VARCHAR step_chargingStatus
        FLOAT step_energyCharged
        FLOAT step_partialCharge
        FLOAT step_power
        FLOAT step_efficiency
        FLOAT step_actualBatteryCapacity
        FLOAT step_maximumBatteryCapacity
        VARCHAR simulation_timestamp
    }
    pricing_data {
        BIGINT statistics_code
        VARCHAR statistics_label
        VARCHAR time_code
        VARCHAR time_label
        BIGINT time
        VARCHAR _1_variable_code
        VARCHAR _1_variable_label
        VARCHAR _1_variable_attribute_code
        VARCHAR _1_variable_attribute_label
        VARCHAR _2_variable_code
        VARCHAR _2_variable_label
        VARCHAR _2_variable_attribute_code
        VARCHAR _2_variable_attribute_label
        VARCHAR _3_variable_code
        VARCHAR _3_variable_label
        VARCHAR _3_variable_attribute_code
        VARCHAR _3_variable_attribute_label
        VARCHAR value
        VARCHAR value_unit
        VARCHAR value_variable_code
        VARCHAR value_variable_label
        VARCHAR value_q
    }
    solar_power_v6 {
        VARCHAR station_id
        DOUBLE _3600
        DOUBLE _7200
        DOUBLE _10800
        DOUBLE _14400
        DOUBLE _18000
        DOUBLE _21600
        DOUBLE _25200
        DOUBLE _28800
        DOUBLE _32400
        DOUBLE _36000
        DOUBLE _39600
        DOUBLE _43200
        DOUBLE _46800
        DOUBLE _50400
        DOUBLE _54000
        DOUBLE _57600
        DOUBLE _61200
        DOUBLE _64800
        DOUBLE _68400
        DOUBLE _72000
        DOUBLE _75600
        DOUBLE _79200
        DOUBLE _82800
        DOUBLE _86400
    }
    tripinfo {
        VARCHAR tripinfo_id
        VARCHAR tripinfo_depart
        VARCHAR tripinfo_departLane
        FLOAT tripinfo_departPos
        FLOAT tripinfo_departSpeed
        VARCHAR tripinfo_departDelay
        VARCHAR tripinfo_arrival
        VARCHAR tripinfo_arrivalLane
        FLOAT tripinfo_arrivalPos
        FLOAT tripinfo_arrivalSpeed
        VARCHAR tripinfo_duration
        FLOAT tripinfo_routeLength
        VARCHAR tripinfo_waitingTime
        INTEGER tripinfo_waitingCount
        VARCHAR tripinfo_stopTime
        VARCHAR tripinfo_timeLoss
        INTEGER tripinfo_rerouteNo
        VARCHAR tripinfo_devices
        VARCHAR tripinfo_vType
        FLOAT tripinfo_speedFactor
        VARCHAR tripinfo_vaporized
        VARCHAR battery_depleted
        VARCHAR battery_actualBatteryCapacity
        VARCHAR battery_totalEnergyConsumed
        VARCHAR battery_totalEnergyRegenerated
        VARCHAR simulation_timestamp
    }