from pathlib import Path

import pandas as pd

from energy_storage_system.charging_station import ChargingStation

MINUTES_PER_HOUR = 60
TOTAL_MINUTES = 1740  # 1 day
# Set to 1740 for entire sim run


def parse_pv_data(csv_path):
    df = pd.read_csv(csv_path)
    df = df.set_index('station_id')
    df = df.drop(columns=["peak_power"])
    df = df[sorted(df.columns, key=lambda c: int(c))]
    return {station_id: row.astype(float).tolist() for station_id, row in df.iterrows()}


def parse_peak_power(csv_path):
    df = pd.read_csv(csv_path, usecols=["station_id", "peak_power"])
    df = df.set_index('station_id')
    return df["peak_power"].astype(float).to_dict()

class EnergyStorageSystem:
    def __init__(self, charging_stations, pv_csv_path, ess_factor=None, ess_capacity=None,
                 output_path=None, start_soc=0.0, pv_factor=1.0):
        """ess_factor sizes each station's ESS as ess_factor * (that station's PV peak power).
        Pass ess_capacity instead to statically set the same capacity for every station,
        bypassing the factor-based calculation.
        start_soc is a fraction (0.0-1.0) of each station's own capacity, not an absolute
        energy value, so every station starts at the same relative charge level.
        pv_factor scales the PV power generated by each station (default 1.0, i.e. no scaling)."""
        self.charging_stations = charging_stations
        self.ess_factor = ess_factor
        self.ess_capacity = ess_capacity
        self.pv_csv_path = pv_csv_path
        self.output_path = output_path
        self.start_soc = start_soc
        self.pv_factor = pv_factor
        self.pv_data = None
        self.peak_power = None
        self.ess_df = None

    def main(self):
        """Run the full ESS pipeline: load PV data, derive load/PV profiles,
        simulate the battery, and write the result to XML if an output_path was given."""
        self.pv_data = parse_pv_data(self.pv_csv_path)
        self.peak_power = parse_peak_power(self.pv_csv_path)
        self.energy_per_timestep(self.charging_stations)
        ess_capacities = self.calculate_ess_capacities(
            self.charging_stations, self.ess_factor, self.ess_capacity
        )
        self.ess_df = self.calculate_ess(self.charging_stations, ess_capacities, self.start_soc)
        if self.output_path is not None:
            self.write_xml(self.output_path)
        return self.ess_df

    def calculate_ess_capacities(self, charging_stations, ess_factor=None, ess_capacity=None):
        """Return {station_id: capacity}. If ess_capacity is given, every station gets that
        static capacity. Otherwise each station's capacity is ess_factor * its PV peak power."""
        if ess_capacity is not None:
            return {station.id: ess_capacity for station in charging_stations}
        if ess_factor is None:
            raise ValueError("Either ess_factor or ess_capacity must be provided.")
        return {
            station.id: self.peak_power[station.id] * ess_factor
            for station in charging_stations
        }

    def energy_per_timestep(self, charging_stations):
        for station in charging_stations:
            for ev in station.charging_events:
                duration_min = (ev.end_sec - ev.begin_sec) / 60
                ev.energy_per_minute = ev.total_energy / duration_min if duration_min > 0 else 0.0
        return charging_stations

    def build_load_profile(self, charging_station, total_minutes=TOTAL_MINUTES):
        load = [0.0] * total_minutes
        for ev in charging_station.charging_events:
            start_sec = max(ev.begin_sec, 0)
            end_sec = min(ev.end_sec, total_minutes * 60)
            if end_sec <= start_sec:
                continue
            start_min = int(start_sec // 60)
            end_min = int(end_sec // 60)
            for t in range(start_min, min(end_min + 1, total_minutes)):
                minute_start, minute_end = t * 60, t * 60 + 60
                overlap = min(end_sec, minute_end) - max(start_sec, minute_start)
                if overlap <= 0:
                    continue
                load[t] += ev.energy_per_minute * (overlap / 60)
        return load

    def get_pv_generated(self, charging_station, hour):
        hourly_values = self.pv_data[charging_station.id]
        return hourly_values[hour % len(hourly_values)] * self.pv_factor

    def build_pv_profile(self, charging_station, total_minutes=TOTAL_MINUTES):
        pv = [0.0] * total_minutes
        for t in range(total_minutes):
            hour = t // MINUTES_PER_HOUR
            pv_hourly = self.get_pv_generated(charging_station, hour)
            pv[t] = pv_hourly / MINUTES_PER_HOUR
        return pv

    def calculate_ess(self, charging_stations, ess_capacities, start_soc=0.0, total_minutes=TOTAL_MINUTES):
        rows = []
        for station in charging_stations:
            load = self.build_load_profile(station, total_minutes)
            pv = self.build_pv_profile(station, total_minutes)
            capacity = ess_capacities[station.id]
            soc = start_soc * capacity
            for t in range(total_minutes):
                net = pv[t] - load[t]
                grid_draw = 0.0
                curtailed_pv = 0.0
                if net >= 0:
                    new_soc = soc + net
                    if new_soc > capacity:
                        curtailed_pv = new_soc - capacity
                        soc = capacity
                    else:
                        soc = new_soc
                else:
                    deficit = -net
                    new_soc = soc - deficit
                    if new_soc < 0:
                        grid_draw = -new_soc
                        soc = 0.0
                    else:
                        soc = new_soc
                rows.append({
                    "station_id": station.id,
                    "timestep_min": t,
                    "pv_generated": pv[t],
                    "energy_charged": load[t],
                    "ess_soc": soc,
                    "grid_energy_drawn": grid_draw,
                    "pv_curtailed": curtailed_pv,
                })
        return pd.DataFrame(rows)

    def write_xml(self, output_path):
        """Write ess_df out as a SUMO-style timestep/station XML file."""
        df = self.ess_df.sort_values(["timestep_min", "station_id"])

        with open(Path(output_path), "w", encoding="utf8") as f:
            f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
            f.write("<ess-export>\n")

            for timestep_min, group in df.groupby("timestep_min"):
                f.write(f'    <timestep time="{timestep_min * 60:.2f}">\n')

                for row in group.itertuples():
                    f.write(
                        f'        <station '
                        f'id="{row.station_id}" '
                        f'pvGenerated="{row.pv_generated:.6f}" '
                        f'energyCharged="{row.energy_charged:.6f}" '
                        f'essSoc="{row.ess_soc:.6f}" '
                        f'gridEnergyDrawn="{row.grid_energy_drawn:.6f}" '
                        f'pvCurtailed="{row.pv_curtailed:.6f}"/>\n'
                    )

                f.write("    </timestep>\n")

            f.write("</ess-export>\n")


if __name__ == "__main__":
    charging_stations = ChargingStation.from_xml(
        r"C:\Users\svens\Documents\FU-Berlin\BeST-eBuS\best-ebus\scenario\sumo\output\electric_bus_2026-08-17-19-10-35_chargingstations.xml"
    )

    EnergyStorageSystem(
        charging_stations=charging_stations,
        ess_factor=1.0,   # each station's ESS = ess_factor * that station's total PV yield (Wh)
        # ess_capacity=500_000,   # or set a static capacity (Wh) for every station instead
        pv_csv_path=r"C:\Users\svens\Documents\FU-Berlin\BeST-eBuS\best-ebus\scenario\eBuS\pv_estimation\data\solar_power_v6_scaled.csv",
        output_path=r"C:\Users\svens\Documents\FU-Berlin\BeST-eBuS\best-ebus\scenario\sumo\output\electric_bus_2026-08-17-19-10-35_ess.xml",
        start_soc=0.5,   # fraction (0.0-1.0) of each station's own ESS capacity
        pv_factor=1.0,   # scales the PV power generated by each station
    ).main()