
from datetime import date
from pathlib import Path

from analysis.output_files import SeedOutputFiles

from energy_storage_system.charging_station import ChargingStation
from energy_storage_system.energy_storage_system import EnergyStorageSystem

PROJECT_ROOT = Path(__file__).resolve().parent
SCENARIO_ROOT = PROJECT_ROOT.parent

SUMO_DIR = SCENARIO_ROOT / "sumo"
SUMO_OUTPUT_DIR = SUMO_DIR / "output"
EBUS_DIR = SCENARIO_ROOT / "eBuS"
FILES_DIR = EBUS_DIR / "files"
PV_DATA_DIR = EBUS_DIR / "pv_estimation/data"

@staticmethod
def run_energy_storage_system( run_dir: Path, start_date: date):
    """
    Build the energy storage system profile from a seed run's SUMO
    chargingstations output (a "<seed>_directory" folder, see
    tools.order_output.order_output) and write the result back as XML.
    Uses the PV data fetched for start_date by run_pvgis_api_call.
    """
    files = SeedOutputFiles(run_dir)
    chargingstations_file = files.get_file("chargingstations")
    output_file = files.output_dir / chargingstations_file.name.replace(
        "_chargingstations.xml", "_ess.xml"
    )
    pv_csv_path = PV_DATA_DIR / f"{start_date}_solar_power_v6_scaled.csv"

    EnergyStorageSystem(
        charging_stations=ChargingStation.from_xml(chargingstations_file),
        ess_factor=2.0,  # each station's ESS = ess_factor * that station's Peak Power (kWh)
        pv_csv_path=pv_csv_path,
        output_path=output_file,
        start_soc=0.2,  # fraction (0.0-1.0) of each station's own ESS capacity
        pv_factor=1.0,  # scales the PV power generated by each station
        grid_charge_max_soc=0.2,  # always draw from grid below this fraction of SoC
        grid_charge_power=50.0,  # power (kW) drawn from grid while below grid_charge_max_soc
        efficiency=0.95,  # battery round-trip efficiency (0.0-1.0)
    ).main()
    print(f"ESS output written to {output_file}")


if __name__ == "__main__":
    run_energy_storage_system(r"C:\Users\svens\Documents\FU-Berlin\BeST-eBuS\best-ebus\scenario\sumo\output\winter_run_2026-09-13-14-57-07\65_directory", "2024-08-22")
    run_energy_storage_system(r"C:\Users\svens\Documents\FU-Berlin\BeST-eBuS\best-ebus\scenario\sumo\output\winter_run_2026-09-13-14-57-07\67_directory", "2024-08-22")
    run_energy_storage_system(r"C:\Users\svens\Documents\FU-Berlin\BeST-eBuS\best-ebus\scenario\sumo\output\winter_run_2026-09-13-14-57-07\68_directory", "2024-08-22")
    run_energy_storage_system(r"C:\Users\svens\Documents\FU-Berlin\BeST-eBuS\best-ebus\scenario\sumo\output\winter_run_2026-09-13-14-57-07\70_directory", "2024-08-22")
    run_energy_storage_system(r"C:\Users\svens\Documents\FU-Berlin\BeST-eBuS\best-ebus\scenario\sumo\output\winter_run_2026-09-13-14-57-07\75_directory", "2024-08-22")
